/*
 * Created on 28 五月 2016 ( Time 12:17:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ayuayu.dao.statement;

import org.springframework.data.jpa.repository.JpaRepository;

import com.ayuayu.model.statement.BalanceSheetIfrs;
import com.ayuayu.model.statement.BalanceSheetIfrsKey;

public interface BalanceSheetIfrsRepository extends
		JpaRepository<BalanceSheetIfrs, BalanceSheetIfrsKey> {
}
