/*
 * Created on 28 五月 2016 ( Time 12:17:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ayuayu.dao.statement;

import org.springframework.data.repository.CrudRepository;

import com.ayuayu.model.statement.CashFlowStatementIfrs;
import com.ayuayu.model.statement.CashFlowStatementIfrsKey;

public interface CashflowStatementIfrsRepository extends
		CrudRepository<CashFlowStatementIfrs, CashFlowStatementIfrsKey> {
}
