/*
 * Created on 1 六月 2016 ( Time 21:34:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key

package com.ayuayu.model.analysis;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table
 * "OPERATING_PERFORMANCE_ANALYSIS_IFRS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "OPERATING_PERFORMANCE_ANALYSIS_IFRS")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "OperatingPerformanceAnalysisIfrs.countAll", query = "SELECT COUNT(x) FROM OperatingPerformanceAnalysisIfrs x") })
public class OperatingPerformanceAnalysisIfrs implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )
	// ----------------------------------------------------------------------
	@EmbeddedId
	private OperatingPerformanceAnalysisIfrsKey compositePrimaryKey;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "ACCOUNTS_RECEIVABLE_TURNOVER_RATIO")
	private Double accountsReceivableTurnoverRatio;

	@Column(name = "ACCOUNTS_RECEIVABLE_TURNOVER_DAYS")
	private Double accountsReceivableTurnoverDays;

	@Column(name = "INVENTORY_TURNOVER_RATIO")
	private Double inventoryTurnoverRatio;

	@Column(name = "INVENTORY_TURNOVER_DAYS")
	private Double inventoryTurnoverDays;

	@Column(name = "FIXED_ASSET_TURNOVER_RATIO")
	private Double fixedAssetTurnoverRatio;

	@Column(name = "TOTAL_ASSET_TURNOVER_RATIO")
	private Double totalAssetTurnoverRatio;

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public OperatingPerformanceAnalysisIfrs() {
		super();
		this.compositePrimaryKey = new OperatingPerformanceAnalysisIfrsKey();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE COMPOSITE KEY
	// ----------------------------------------------------------------------
	public void setStockId(String stockId) {
		this.compositePrimaryKey.setStockId(stockId);
	}

	public String getStockId() {
		return this.compositePrimaryKey.getStockId();
	}

	public void setYear(Short year) {
		this.compositePrimaryKey.setYear(year);
	}

	public Short getYear() {
		return this.compositePrimaryKey.getYear();
	}

	public void setSeason(Byte season) {
		this.compositePrimaryKey.setSeason(season);
	}

	public Byte getSeason() {
		return this.compositePrimaryKey.getSeason();
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : ACCOUNTS_RECEIVABLE_TURNOVER_RATIO ( DOUBLE )
	public void setAccountsReceivableTurnoverRatio(
			Double accountsReceivableTurnoverRatio) {
		this.accountsReceivableTurnoverRatio = accountsReceivableTurnoverRatio;
	}

	public Double getAccountsReceivableTurnoverRatio() {
		return this.accountsReceivableTurnoverRatio;
	}

	// --- DATABASE MAPPING : ACCOUNTS_RECEIVABLE_TURNOVER_DAYS ( DOUBLE )
	public void setAccountsReceivableTurnoverDays(
			Double accountsReceivableTurnoverDays) {
		this.accountsReceivableTurnoverDays = accountsReceivableTurnoverDays;
	}

	public Double getAccountsReceivableTurnoverDays() {
		return this.accountsReceivableTurnoverDays;
	}

	// --- DATABASE MAPPING : INVENTORY_TURNOVER_RATIO ( DOUBLE )
	public void setInventoryTurnoverRatio(Double inventoryTurnoverRatio) {
		this.inventoryTurnoverRatio = inventoryTurnoverRatio;
	}

	public Double getInventoryTurnoverRatio() {
		return this.inventoryTurnoverRatio;
	}

	// --- DATABASE MAPPING : INVENTORY_TURNOVER_DAYS ( DOUBLE )
	public void setInventoryTurnoverDays(Double inventoryTurnoverDays) {
		this.inventoryTurnoverDays = inventoryTurnoverDays;
	}

	public Double getInventoryTurnoverDays() {
		return this.inventoryTurnoverDays;
	}

	// --- DATABASE MAPPING : FIXED_ASSET_TURNOVER_RATIO ( DOUBLE )
	public void setFixedAssetTurnoverRatio(Double fixedAssetTurnoverRatio) {
		this.fixedAssetTurnoverRatio = fixedAssetTurnoverRatio;
	}

	public Double getFixedAssetTurnoverRatio() {
		return this.fixedAssetTurnoverRatio;
	}

	// --- DATABASE MAPPING : TOTAL_ASSET_TURNOVER_RATIO ( DOUBLE )
	public void setTotalAssetTurnoverRatio(Double totalAssetTurnoverRatio) {
		this.totalAssetTurnoverRatio = totalAssetTurnoverRatio;
	}

	public Double getTotalAssetTurnoverRatio() {
		return this.totalAssetTurnoverRatio;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		if (compositePrimaryKey != null) {
			sb.append(compositePrimaryKey.toString());
		} else {
			sb.append("(null-key)");
		}
		sb.append("]:");
		sb.append(accountsReceivableTurnoverRatio);
		sb.append("|");
		sb.append(accountsReceivableTurnoverDays);
		sb.append("|");
		sb.append(inventoryTurnoverRatio);
		sb.append("|");
		sb.append(inventoryTurnoverDays);
		sb.append("|");
		sb.append(fixedAssetTurnoverRatio);
		sb.append("|");
		sb.append(totalAssetTurnoverRatio);
		return sb.toString();
	}

}
