/*
 * Created on 28 五月 2016 ( Time 12:17:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ayuayu.dao.analysis;

import org.springframework.data.jpa.repository.JpaRepository;

import com.ayuayu.model.analysis.CapitalStructureAnalysisIfrs;
import com.ayuayu.model.analysis.CapitalStructureAnalysisIfrsKey;

public interface CapitalStructureAnalysisIfrsRepository
		extends
		JpaRepository<CapitalStructureAnalysisIfrs, CapitalStructureAnalysisIfrsKey> {
}
