DROP TABLE STOCK_META IF EXISTS;
DROP TABLE BALANCE_SHEET_GAAP IF EXISTS;
DROP TABLE BALANCE_SHEET_IFRS IF EXISTS;
DROP TABLE CASH_FLOW_STATEMENT_GAAP IF EXISTS;
DROP TABLE CASH_FLOW_STATEMENT_IFRS IF EXISTS;
DROP TABLE INCOME_STATEMENT_GAAP IF EXISTS;
DROP TABLE INCOME_STATEMENT_IFRS IF EXISTS;
DROP TABLE CAPITAL_STRUCTURE_ANALYSIS_GAAP IF EXISTS;
DROP TABLE CAPITAL_STRUCTURE_ANALYSIS_IFRS IF EXISTS;
DROP TABLE LIQUIDITY_ANALYSIS_GAAP IF EXISTS;
DROP TABLE LIQUIDITY_ANALYSIS_IFRS IF EXISTS;
DROP TABLE OPERATING_PERFORMANCE_ANALYSIS_GAAP IF EXISTS;
DROP TABLE OPERATING_PERFORMANCE_ANALYSIS_IFRS IF EXISTS;
DROP TABLE RETRUN_ON_INVESTMENT_ANALYSIS_GAAP IF EXISTS;
DROP TABLE RETRUN_ON_INVESTMENT_ANALYSIS_IFRS IF EXISTS;
DROP TABLE CASH_FLOW_ANALYSIS_GAAP IF EXISTS;
DROP TABLE CASH_FLOW_ANALYSIS_IFRS IF EXISTS;

CREATE TABLE STOCK_META
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL
);

CREATE TABLE BALANCE_SHEET_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
ASSETS BIGINT,
CURRENT_ASSETS BIGINT,
CASH_AND_CASH_EQUIVALENTS BIGINT,
INVENTORIES BIGINT,
PREPAYMENTS BIGINT,
NOTES_RECEIVABLE_NET BIGINT,
ACCOUNTS_RECEIVABLE_NET BIGINT,
ACCOUNTS_RECEIVABLE_DUEFROM_RELATED_PARTIES_NET BIGINT,
OTHER_RECEIVABLES_DUE_FROM_RELATED_PARTIES BIGINT,
OTHER_CURRENT_ASSETS BIGINT,
PROPERTY_PLANT_AND_EQUIPMENT BIGINT,
INVESTMENT_PROPERTY BIGINT,
INVESTMENT_ACCOUNTED_FOR_USING_EQUITY_METHOD BIGINT,
NONCURRENT_ASSETS BIGINT,
NONCURRENT_AVAILABLE_FOR_SALE_FINANCIAL_ASSETS BIGINT,
NONCURRENT_FINANCIAL_ASSETS_AT_COST BIGINT,
OTHER_NONCURRENT_ASSETS BIGINT,
LIABILITIES BIGINT,
CURRENT_LIABILITIES BIGINT,
NONCURRENT_LIABILITIES BIGINT,
OTHER_NONCURRENT_LIABILITIES BIGINT,
EQUITY BIGINT
);

CREATE TABLE CASH_FLOW_STATEMENT_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
CASH_FLOWS_FROM_USED_IN_OPERATING_ACTIVITIES BIGINT,
INTEREST_EXPENSE BIGINT,
NET_CASH_FLOWS_FROM_USED_IN_INVESTING_ACTIVITIES BIGINT,
ACQUISITION_OF_PROPERTY_PLANT_AND_EQUIPMENT BIGINT,
DECREASE_INCREASE_IN_INVENTORIES BIGINT,
CASH_FLOWS_FROM_USED_IN_FINANCING_ACTIVITIES BIGINT,
CASH_DIVIDENDS_PAID BIGINT,
DEPRECIATION_EXPENSE BIGINT,
AMORTIZATION_EXPENSE BIGINT
);

CREATE TABLE INCOME_STATEMENT_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
OPERATING_REVENUE BIGINT,
OPERATING_COSTS BIGINT,
GROSS_PROFIT_LOSS_FROM_OPERATIONS BIGINT,
REALIZED_PROFIT_LOSS_ON_FROM_SALES BIGINT,
OPERATING_EXPENSES BIGINT,
NET_OPERATING_INCOME_LOSS BIGINT,
NONOPERATING_INCOME_AND_EXPENSES BIGINT,
PROFIT_LOSS_BEFORE_TAX BIGINT,
INCOME_TAX_EXPENSE_CONTINUING_OPERATIONS BIGINT,
PROFIT_LOSS_FROM_CONTINUING_OPERATIONS BIGINT,
BASIC_EARNINGS_LOSS_PER_SHARE DOUBLE
);

CREATE TABLE CAPITAL_STRUCTURE_ANALYSIS_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
DEBT_RATIO DOUBLE,
DEBT_EQUITY_RATIO DOUBLE,
LONG_TERM_FUNDS_TO_PROPERTY_PLANT_AND_EQUIPMENT DOUBLE
);

CREATE TABLE LIQUIDITY_ANALYSIS_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
CURRENT_RATIO DOUBLE,
QUICK_RATIO DOUBLE,
INTEREST_GUARANTEE DOUBLE
);

CREATE TABLE OPERATING_PERFORMANCE_ANALYSIS_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
ACCOUNTS_RECEIVABLE_TURNOVER_RATIO DOUBLE,
ACCOUNTS_RECEIVABLE_TURNOVER_DAYS DOUBLE,
INVENTORY_TURNOVER_RATIO DOUBLE,
INVENTORY_TURNOVER_DAYS DOUBLE,
FIXED_ASSET_TURNOVER_RATIO DOUBLE,
TOTAL_ASSET_TURNOVER_RATIO DOUBLE
);

CREATE TABLE RETRUN_ON_INVESTMENT_ANALYSIS_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
ROA DOUBLE,
ROE DOUBLE,
GROSS_PROFIT_MARGIN DOUBLE,
OPERATING_PROFIT_MARGIN DOUBLE,
PRE_TAX_NET_PROFIT_MARGIN DOUBLE,
NET_PROFIT_MARGIN DOUBLE
);

CREATE TABLE CASH_FLOW_ANALYSIS_IFRS
(
STOCK_ID VARCHAR(5) NOT NULL,
YEAR SMALLINT NOT NULL,
SEASON TINYINT NOT NULL,
CASH_FLOW_RATIO DOUBLE,
CASH_REINVESTMENT_RATIO DOUBLE
);

ALTER TABLE STOCK_META ADD CONSTRAINT PK_SM_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE BALANCE_SHEET_IFRS ADD CONSTRAINT PK_BS_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE CASH_FLOW_STATEMENT_IFRS ADD CONSTRAINT PK_CFS_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE INCOME_STATEMENT_IFRS ADD CONSTRAINT PK_IS_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE CAPITAL_STRUCTURE_ANALYSIS_IFRS ADD CONSTRAINT PK_CSA_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE LIQUIDITY_ANALYSIS_IFRS ADD CONSTRAINT PK_LA_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE OPERATING_PERFORMANCE_ANALYSIS_IFRS ADD CONSTRAINT PK_OPA_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE RETRUN_ON_INVESTMENT_ANALYSIS_IFRS ADD CONSTRAINT PK_ROIA_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);
ALTER TABLE CASH_FLOW_ANALYSIS_IFRS ADD CONSTRAINT PK_CFA_ID PRIMARY KEY (STOCK_ID,YEAR,SEASON);

--ALTER TABLE BALANCE_SHEET_IFRS ADD FOREIGN KEY (STOCK_ID) REFERENCES STOCK_META(STOCK_ID);
--ALTER TABLE BALANCE_SHEET_IFRS ADD FOREIGN KEY (YEAR) REFERENCES STOCK_META(YEAR);
--ALTER TABLE BALANCE_SHEET_IFRS ADD FOREIGN KEY (SEASON) REFERENCES STOCK_META(SEASON);

